function renderAll(){renderDash();renderCusts();renderSel();renderAllTx();renderRep()}
function renderDash(){var t={SYP:{d:0,c:0},USD:{d:0,c:0}},j=0;TX.forEach(x=>{if(x.type==='D')t[x.cur].d+=x.total;else t[x.cur].c+=x.total;j+=(+x.qty||0)});
 var h='';for(var k in t){h+='<div class="kpi r"><div class="l">عليه ('+CURR[k]+')</div><div class="v neg">'+f2(t[k].d)+'</div></div><div class="kpi g"><div class="l">له ('+CURR[k]+')</div><div class="v pos">'+f2(t[k].c)+'</div></div>'}
 h+='<div class="kpi"><div class="l">الزبائن</div><div class="v">'+CUST.length+'</div></div>';
 $('#dash').innerHTML=h;
 $('#lastTx').innerHTML=TX.slice(-6).reverse().map(function(x){return '<div style="display:flex;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line);font-size:12.5px"><b style="flex:1">'+cname(x.cust)+'</b><span class="num '+(x.type==='D'?'neg':'pos')+'">'+f2(x.total)+' '+CURR[x.cur]+'</span></div>'}).join('')||'<p style="color:var(--mut);font-size:12px">لا حركات.</p>'}
function renderCusts(){var q=($('#cSearch').value||'').toLowerCase();var l=CUST.filter(c=>!q||c.name.toLowerCase().indexOf(q)>=0);
 $('#custList').innerHTML=l.map(c=>'<div class="cust" onclick="openCust('+c.id+')"><div class="av">'+c.name.charAt(0)+'</div><div class="info"><b>'+c.name+'</b><small>'+(c.phone||'بدون رقم')+'</small></div><div class="bal"><div class="amt">'+fmtBal(bal(c.id))+'</div></div><button class="ib d" onclick="event.stopPropagation();delCustById('+c.id+')" style="margin-right:6px">🗑</button></div>').join('')||'<p style="color:var(--mut);font-size:12px">لا زبائن.</p>'}
function renderSel(){$('#tCust').innerHTML=CUST.map(c=>'<option value="'+c.id+'">'+c.name+'</option>').join('')||'<option value="">— أضف زبوناً —</option>'}
function renderAllTx(){$('#allTx').innerHTML='<table class="tbl"><thead><tr><th>الزبون</th><th>التاريخ</th><th>النوع</th><th>المجموع</th><th></th></tr></thead><tbody>'+TX.slice().reverse().map(x=>'<tr><td>'+cname(x.cust)+'</td><td class="num">'+x.date+'</td><td class="'+(x.type==='D'?'neg':'pos')+'">'+(x.type==='D'?'عليه':'له')+'</td><td class="num">'+f2(x.total)+' '+CURR[x.cur]+'</td><td><button class="ib e" onclick="startEdit('+x.id+')">✏️</button><button class="ib d" onclick="delTx('+x.id+')">🗑</button></td></tr>').join('')+'</tbody></table>'}
function renderRep(){$('#rDayBody').innerHTML=sumTable(TX.filter(x=>x.date===$('#rDay').value),true);$('#rMonthBody').innerHTML=sumTable(TX.filter(x=>x.date.slice(0,7)===$('#rMonth').value),false)}
function sumTable(tx,wd){var t={SYP:{d:0,c:0},USD:{d:0,c:0}};tx.forEach(x=>{if(x.type==='D')t[x.cur].d+=x.total;else t[x.cur].c+=x.total});
 var h='<table class="tbl"><thead><tr>'+(wd?'<th>التاريخ</th>':'')+'<th>الزبون</th><th>عليه</th><th>له</th></tr></thead><tbody>'+tx.map(x=>'<tr>'+(wd?'<td class="num">'+x.date+'</td>':'')+'<td>'+cname(x.cust)+'</td><td class="num neg">'+(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'—')+'</td><td class="num pos">'+(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'—')+'</td></tr>').join('')+'</tbody></table>';
 var s='';for(var k in t){s+='<p style="font-size:12px;margin-top:6px">'+CURR[k]+': عليه <b class="neg">'+f2(t[k].d)+'</b> — له <b class="pos">'+f2(t[k].c)+'</b></p>'}return h+s}
function th(c){return '<th style="border:1px solid #000;padding:7px">'+c+'</th>'}
function td(v){return '<td style="border:1px solid #000;padding:6px">'+v+'</td>'}
/* 📄 تصدير PDF بنص حقيقي قابل للبحث */
function sheetPDF(html,name){var w=window.open('','_blank');if(!w){toast('❌ اسمح بالنوافذ المنبثقة');return}
w.document.write('<html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>'+name+'</title><style>@page{margin:12mm}body{font-family:Tajawal,Arial,sans-serif;color:#000;background:#fff}h1{text-align:center;border-bottom:3px double #000;padding-bottom:8px;margin-bottom:16px}table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}th,td{border:1px solid #000;padding:6px;text-align:right}th{background:#eee;font-weight:bold}.neg{color:#c00}.pos{color:#080}</style></head><body>'+html+'<script>window.onload=function(){setTimeout(function(){window.print()},500)}<\/script></body></html>');
w.document.close();toast('🖨 اختر "حفظ كـ PDF" — النص قابل للبحث ✔')}
function exportAllPDF(){sheetPDF('<h1>الجرد الكامل</h1><table><tr>'+th('الزبون')+th('التاريخ')+th('عليه')+th('له')+'</tr>'+TX.map(x=>'<tr>'+td(cname(x.cust))+td(x.date)+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','الجرد الكامل')}
function exportDayPDF(){var d=$('#rDay').value;var tx=TX.filter(x=>x.date===d);sheetPDF('<h1>يومي — '+d+'</h1><table><tr>'+th('الزبون')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(cname(x.cust))+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','يومي-'+d)}
function exportRepPDF(){var m=$('#rMonth').value;var tx=TX.filter(x=>x.date.slice(0,7)===m);sheetPDF('<h1>شهري — '+m+'</h1><table><tr>'+th('الزبون')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(cname(x.cust))+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','شهري-'+m)}
function exportCustPDF(){var c=CUST.filter(x=>x.id===curCust)[0];var tx=TX.filter(x=>x.cust===curCust);
 sheetPDF('<h1>كشف: '+c.name+'</h1><table><tr>'+th('التاريخ')+th('البيان')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(x.date)+td(x.note||'—')+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table><p style="font-size:15px;font-weight:800;margin-top:20px">الرصيد: '+fmtBal(bal(curCust))+'</p>','كشف-'+c.name)}
/* 🗑 حذف نهائي لزبون من القائمة مباشرة */
function delCustById(id){var c=CUST.filter(x=>x.id===id)[0];if(!c||!confirm('حذف '+c.name+' وكل حركاته نهائياً (جهاز + سحابة)؟'))return;CUST=CUST.filter(x=>x.id!==id);TX=TX.filter(x=>x.cust!==id);SV('fr_cust',CUST);SV('fr_tx',TX);renderAll();cloudSave();speak('تم حذف '+c.name);toast('🗑 حُذف نهائياً')}
if('serviceWorker' in navigator)navigator.serviceWorker.register('farouk-sw.js').catch(function(){});
if(sessionStorage.getItem('fr_ok'))enter();
