function renderAll(){renderDash();renderCusts();renderSel();renderAllTx();renderRep();renderFin();renderDrv();
 if($('#s-drvview')&&$('#s-drvview').classList.contains('on'))renderDrvView();
 if($('#s-view')&&$('#s-view').classList.contains('on'))renderCustView()}
/* 🧱 بناء التبويبات الجديدة وحقل السائق ورقم الواتساب (تلقائياً) */
function buildExtra(){var nav=document.querySelector('.nav');
 if(!$('#navFin')){var b1=document.createElement('button');b1.id='navFin';b1.textContent='💰 المالية';b1.onclick=function(){go('fin',this)};nav.insertBefore(b1,nav.lastElementChild);
  var b2=document.createElement('button');b2.id='navDrv';b2.textContent='🚚 السائقين';b2.onclick=function(){go('drv',this)};nav.insertBefore(b2,nav.lastElementChild)}
 if(!$('#s-fin')){var w=document.querySelector('.wrap');
  w.insertAdjacentHTML('beforeend','<section class="sec" id="s-fin"><div class="card"><h3>💰 المالية — المربح بيحسب لحاله</h3><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px"><button class="btn b1" onclick="addFin(\'cap\')">➕ رأس مال</button><button class="btn b2" onclick="addFin(\'exp\')">➕ مصروف</button></div><div class="kpis" id="finKpis"></div><div id="finList"></div></div></section>');
  w.insertAdjacentHTML('beforeend','<section class="sec" id="s-drv"><div class="card"><h3>🚚 السائقين وحساباتهم (عليه/له)</h3><button class="btn b1" style="width:100%;margin-bottom:10px" onclick="addDrv()">➕ إضافة سائق</button><div id="drvList"></div></div></section>');
  w.insertAdjacentHTML('beforeend','<section class="sec" id="s-drvview"><div class="vhead"><button class="btn b2" onclick="go(\'drv\',document.getElementById(\'navDrv\'))">← رجوع</button><h2 id="dvName"></h2></div><div class="card" style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn b1" onclick="addDTX(curDrv,\'D\')">➕ عليه</button><button class="btn b2" onclick="addDTX(curDrv,\'C\')">➕ له</button><button class="btn bw" onclick="waDrv(curDrv)">💬 واتساب</button><button class="btn br" onclick="delDrv(curDrv)">🗑 حذف السائق</button></div><div class="kpis" id="dvBal"></div><div class="card"><div id="dvTx"></div></div></section>')}
 if(!$('#tDrv')){var payL=$('#tPayment').previousElementSibling;var wr=document.createElement('div');wr.innerHTML='<label class="lb">السائق (الدفعة والجرات معه)</label><select class="in" id="tDrv"></select>';while(wr.firstChild)payL.parentElement.insertBefore(wr.firstChild,payL)}
 if(!$('#cPhone')){var bn=$('#cNew').nextElementSibling;var ip=document.createElement('input');ip.className='in';ip.id='cPhone';ip.placeholder='رقم واتساب (اختياري)';ip.style.margin='0';bn.parentElement.insertBefore(ip,bn)}}
/* 🏠 الرئيسية */
function renderDash(){var t={SYP:{d:0,c:0},USD:{d:0,c:0}};TX.forEach(x=>{if(x.type==='D')t[x.cur].d+=x.total;else t[x.cur].c+=x.total});
 var h='';for(var k in t){h+='<div class="kpi r"><div class="l">عليه ('+CURR[k]+')</div><div class="v neg">'+f2(t[k].d)+'</div></div><div class="kpi g"><div class="l">له ('+CURR[k]+')</div><div class="v pos">'+f2(t[k].c)+'</div></div>'}
 h+='<div class="kpi"><div class="l">الزبائن</div><div class="v">'+CUST.length+'</div></div><div class="kpi"><div class="l">السائقين</div><div class="v">'+DRV.length+'</div></div>';
 $('#dash').innerHTML=h;
 $('#lastTx').innerHTML=TX.slice(-6).reverse().map(function(x){return '<div style="display:flex;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line);font-size:12.5px"><b style="flex:1">'+cname(x.cust)+(x.driver?' 🚚'+dname(x.driver):'')+'</b><span class="num '+(x.type==='D'?'neg':'pos')+'">'+f2(x.total)+' '+CURR[x.cur]+'</span></div>'}).join('')||'<p style="color:var(--mut);font-size:12px">لا حركات.</p>'}
/* 👥 الزبائن + واتساب + حذف مباشر */
function renderCusts(){var q=($('#cSearch').value||'').toLowerCase();var l=CUST.filter(c=>!q||c.name.toLowerCase().indexOf(q)>=0);
 $('#custList').innerHTML=l.map(c=>'<div class="cust" onclick="openCust('+c.id+')"><div class="av">'+c.name.charAt(0)+'</div><div class="info"><b>'+c.name+'</b><small>'+(c.phone||'بدون رقم')+'</small></div><div class="bal"><div class="amt">'+fmtBal(bal(c.id))+'</div></div><span style="display:flex;gap:4px"><button class="ib e" onclick="event.stopPropagation();waCust('+c.id+')">💬</button><button class="ib d" onclick="event.stopPropagation();delCustById('+c.id+')">🗑</button></span></div>').join('')||'<p style="color:var(--mut);font-size:12px">لا زبائن.</p>'}
function delCustById(id){var c=CUST.filter(x=>x.id===id)[0];if(!c||!confirm('حذف '+c.name+' وكل حركاته نهائياً؟'))return;CUST=CUST.filter(x=>x.id!==id);TX=TX.filter(x=>x.cust!==id);SV('fr_cust',CUST);SV('fr_tx',TX);renderAll();cloudSave();toast('🗑 حُذف نهائياً')}
function renderSel(){$('#tCust').innerHTML=CUST.map(c=>'<option value="'+c.id+'">'+c.name+'</option>').join('')||'<option value="">— أضف زبوناً —</option>';
 if($('#tDrv'))$('#tDrv').innerHTML='<option value="0">بدون سائق</option>'+DRV.map(d=>'<option value="'+d.id+'">🚚 '+d.name+'</option>').join('')}
function renderCustView(){var c=CUST.filter(x=>x.id===curCust)[0];if(!c)return;$('#vName').textContent=c.name;
 $('#vBal').innerHTML='<div class="kpi"><div class="l">الرصيد</div><div class="v">'+fmtBal(bal(curCust))+'</div></div><div class="kpi"><div class="l">جرات</div><div class="v">'+jars(curCust)+'</div></div>';
 var tx=TX.filter(x=>x.cust===curCust);
 $('#vTx').innerHTML='<table class="tbl"><thead><tr><th>التاريخ</th><th>البيان</th><th>عليه</th><th>له</th><th></th></tr></thead><tbody>'+tx.map(x=>'<tr><td class="num">'+x.date+'</td><td>'+(x.note||'—')+(x.driver?' 🚚'+dname(x.driver):'')+'</td><td class="num neg">'+(x.type==='D'?f2(x.total):'—')+'</td><td class="num pos">'+(x.type==='C'?f2(x.total):'—')+'</td><td><button class="ib e" onclick="startEdit('+x.id+')">✏️</button><button class="ib d" onclick="delTx('+x.id+')">🗑</button></td></tr>').join('')+'</tbody></table>'}
/* 📋 الجرد والتقارير */
function renderAllTx(){$('#allTx').innerHTML='<table class="tbl"><thead><tr><th>الزبون</th><th>التاريخ</th><th>النوع</th><th>المجموع</th><th></th></tr></thead><tbody>'+TX.slice().reverse().map(x=>'<tr><td>'+cname(x.cust)+'</td><td class="num">'+x.date+'</td><td class="'+(x.type==='D'?'neg':'pos')+'">'+(x.type==='D'?'عليه':'له')+'</td><td class="num">'+f2(x.total)+' '+CURR[x.cur]+'</td><td><button class="ib e" onclick="startEdit('+x.id+')">✏️</button><button class="ib d" onclick="delTx('+x.id+')">🗑</button></td></tr>').join('')+'</tbody></table>'}
function renderRep(){$('#rDayBody').innerHTML=sumTable(TX.filter(x=>x.date===$('#rDay').value),true);$('#rMonthBody').innerHTML=sumTable(TX.filter(x=>x.date.slice(0,7)===$('#rMonth').value),false)}
function sumTable(tx,wd){var t={SYP:{d:0,c:0},USD:{d:0,c:0}};tx.forEach(x=>{if(x.type==='D')t[x.cur].d+=x.total;else t[x.cur].c+=x.total});
 var h='<table class="tbl"><thead><tr>'+(wd?'<th>التاريخ</th>':'')+'<th>الزبون</th><th>عليه</th><th>له</th></tr></thead><tbody>'+tx.map(x=>'<tr>'+(wd?'<td class="num">'+x.date+'</td>':'')+'<td>'+cname(x.cust)+'</td><td class="num neg">'+(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'—')+'</td><td class="num pos">'+(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'—')+'</td></tr>').join('')+'</tbody></table>';
 var s='';for(var k in t){s+='<p style="font-size:12px;margin-top:6px">'+CURR[k]+': عليه <b class="neg">'+f2(t[k].d)+'</b> — له <b class="pos">'+f2(t[k].c)+'</b></p>'}return h+s}
/* 💰 المالية: إضافة + تعديل + حذف + مربح تلقائي */
function renderFin(){var s=finSums();
 $('#finKpis').innerHTML='<div class="kpi g"><div class="l">رأس المال</div><div class="v pos">'+f2(s.cap)+'</div></div><div class="kpi r"><div class="l">المصروفات</div><div class="v neg">'+f2(s.exp)+'</div></div><div class="kpi"><div class="l">الإيراد المقبوض</div><div class="v">'+f2(s.rev)+'</div></div><div class="kpi g"><div class="l">المربح (تلقائي)</div><div class="v pos">'+f2(s.prof)+'</div></div><div class="kpi"><div class="l">الصافي الكلي</div><div class="v">'+f2(s.net)+'</div></div>';
 $('#finList').innerHTML='<table class="tbl"><thead><tr><th>التاريخ</th><th>النوع</th><th>البيان</th><th>المبلغ</th><th></th></tr></thead><tbody>'+FIN.slice().reverse().map(f=>'<tr><td class="num">'+f.date+'</td><td>'+(f.type==='cap'?'رأس مال':'مصروف')+'</td><td>'+(f.note||'—')+'</td><td class="num '+(f.type==='cap'?'pos':'neg')+'">'+f2(f.amt)+'</td><td><button class="ib e" onclick="editFin('+f.id+')">✏️</button><button class="ib d" onclick="delFin('+f.id+')">🗑</button></td></tr>').join('')+'</tbody></table>'}
function editFin(id){var f=FIN.filter(x=>x.id===id)[0];if(!f)return;var a=prompt('المبلغ:',f.amt);if(a&&+a)f.amt=+a;var n=prompt('البيان:',f.note||'');if(n!==null)f.note=n;SV('fr_fin',FIN);renderAll();cloudSave();toast('✏️ عُدّل')}
/* 🚚 السائقين */
function renderDrv(){var L=$('#drvList');if(!L)return;
 L.innerHTML=DRV.map(d=>{var b=drvBal(d.id);return '<div class="cust" onclick="openDrv('+d.id+')"><div class="av">🚚</div><div class="info"><b>'+d.name+'</b><small>'+(d.phone||'بدون رقم')+' • جرات معه: '+drvJars(d.id)+'</small></div><div class="bal"><div class="amt">'+((b.d||b.c)?'عليه '+f2(b.d)+' • له '+f2(b.c):'مسدّد ✔')+'</div></div><button class="ib d" onclick="event.stopPropagation();delDrv('+d.id+')">🗑</button></div>'}).join('')||'<p style="color:var(--mut);font-size:12px">لا سائقين — ضيف أول سائق.</p>'}
function delDrv(id){var d=DRV.filter(x=>x.id===id)[0];if(!d||!confirm('حذف السائق '+d.name+' وكل دفعاته؟'))return;DRV=DRV.filter(x=>x.id!==id);DTX=DTX.filter(x=>x.drv!==id);SV('fr_drv',DRV);SV('fr_dtx',DTX);renderAll();cloudSave();toast('🗑 حُذف')}
function renderDrvView(){var d=DRV.filter(x=>x.id===curDrv)[0];if(!d)return;$('#dvName').textContent='🚚 '+d.name;var b=drvBal(d.id);
 $('#dvBal').innerHTML='<div class="kpi r"><div class="l">عليه</div><div class="v neg">'+f2(b.d)+'</div></div><div class="kpi g"><div class="l">له</div><div class="v pos">'+f2(b.c)+'</div></div><div class="kpi"><div class="l">الصافي</div><div class="v">'+f2(b.d-b.c)+'</div></div><div class="kpi"><div class="l">جرات معه</div><div class="v">'+drvJars(d.id)+'</div></div>';
 $('#dvTx').innerHTML='<table class="tbl"><thead><tr><th>التاريخ</th><th>البيان</th><th>عليه</th><th>له</th><th></th></tr></thead><tbody>'+DTX.filter(t=>t.drv===curDrv).map(t=>'<tr><td class="num">'+t.date+'</td><td>'+(t.note||'—')+'</td><td class="num neg">'+(t.type==='D'?f2(t.amt):'—')+'</td><td class="num pos">'+(t.type==='C'?f2(t.amt):'—')+'</td><td><button class="ib e" onclick="editDTX('+t.id+')">✏️</button><button class="ib d" onclick="delDTX('+t.id+')">🗑</button></td></tr>').join('')+'</tbody></table>'}
function editDTX(id){var t=DTX.filter(x=>x.id===id)[0];if(!t)return;var a=prompt('المبلغ:',t.amt);if(a&&+a)t.amt=+a;var n=prompt('البيان:',t.note||'');if(n!==null)t.note=n;SV('fr_dtx',DTX);renderAll();cloudSave();toast('✏️ عُدّل')}
function delDTX(id){if(!confirm('حذف؟'))return;DTX=DTX.filter(x=>x.id!==id);SV('fr_dtx',DTX);renderAll();cloudSave();toast('🗑')}
/* 📄 PDF بنص قابل للبحث */
function th(c){return '<th style="border:1px solid #000;padding:7px">'+c+'</th>'}
function td(v){return '<td style="border:1px solid #000;padding:6px">'+v+'</td>'}
function sheetPDF(html,name){var w=window.open('','_blank');if(!w){toast('❌ اسمح بالنوافذ المنبثقة');return}
w.document.write('<html dir="rtl" lang="ar"><head><meta charset="utf-8"><title>'+name+'</title><style>@page{margin:12mm}body{font-family:Tajawal,Arial;color:#000;background:#fff}h1{text-align:center;border-bottom:3px double #000;padding-bottom:8px;margin-bottom:16px}table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}th,td{border:1px solid #000;padding:6px;text-align:right}th{background:#eee}</style></head><body>'+html+'<script>window.onload=function(){setTimeout(function(){window.print()},500)}<\/script></body></html>');
w.document.close();toast('🖨 اختر «حفظ كـ PDF» — النص قابل للبحث ✔')}
function exportAllPDF(){sheetPDF('<h1>الجرد الكامل</h1><table><tr>'+th('الزبون')+th('التاريخ')+th('عليه')+th('له')+'</tr>'+TX.map(x=>'<tr>'+td(cname(x.cust))+td(x.date)+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','الجرد الكامل')}
function exportDayPDF(){var d=$('#rDay').value;var tx=TX.filter(x=>x.date===d);sheetPDF('<h1>يومي — '+d+'</h1><table><tr>'+th('الزبون')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(cname(x.cust))+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','يومي-'+d)}
function exportRepPDF(){var m=$('#rMonth').value;var tx=TX.filter(x=>x.date.slice(0,7)===m);sheetPDF('<h1>شهري — '+m+'</h1><table><tr>'+th('الزبون')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(cname(x.cust))+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table>','شهري-'+m)}
function exportCustPDF(){var c=CUST.filter(x=>x.id===curCust)[0];var tx=TX.filter(x=>x.cust===curCust);
 sheetPDF('<h1>كشف: '+c.name+'</h1><table><tr>'+th('التاريخ')+th('البيان')+th('عليه')+th('له')+'</tr>'+tx.map(x=>'<tr>'+td(x.date)+td(x.note||'—')+td(x.type==='D'?f2(x.total)+' '+CURR[x.cur]:'')+td(x.type==='C'?f2(x.total)+' '+CURR[x.cur]:'')+'</tr>').join('')+'</table><p style="font-size:15px;font-weight:800;margin-top:20px">الرصيد: '+fmtBal(bal(curCust))+'</p>','كشف-'+c.name)}
if('serviceWorker' in navigator)navigator.serviceWorker.register('farouk-sw.js').catch(function(){});
if(sessionStorage.getItem('fr_ok'))enter();
